### ISSUE TITLE
Profile Page FE

### ISSUE THREAD

**Issue by jovantanyk** [NUS-Fintech-Society/SD_DAO#27]
Profile Page front end design
Get background from google drive, pending user data from backend
Assigned to @benjytan45678

**Comment by benjytan45678** [comment]
<img width="1398" alt="Screenshot 2023-02-05 at 1 31 54 AM" src="https://user-images.githubusercontent.com/71542870/216781396-e31452b5-203a-4a11-b4c7-53ad518bdc2c.png">

Is this alright?

**Comment by jovantanyk** [comment]
Yup! LGTM
