### ISSUE TITLE
View Proposal Page

### ISSUE THREAD

**Issue by jovantanyk** [NUS-Fintech-Society/SD_DAO#28]
- [x] Proposal Component Box
- [x] Page design
- [x] New Proposal Button
- [x] To get Proposal Title and min stake async from InfuraProvider (@jovantanyk )
Assigned to @loyhongshenggg

**Comment by loyhongshenggg** [comment]
![image](https://user-images.githubusercontent.com/97422591/216781475-14bc29bb-9ec5-4804-9cf9-95e360cd249b.png)
![image](https://user-images.githubusercontent.com/97422591/216781490-68fdb959-b60e-4406-b337-daf6cdd2dbe8.png)
LTGM?

For api, ipfsHash variable is not defined. May need another component to pass in as props.

**Comment by benjytan45678** [comment]
LGTM

**Comment by jovantanyk** [comment]
LGTM! Will settle ipfs hash in a seperate BE commit. Thank you!
