### ISSUE TITLE
Project About Page

### ISSUE THREAD

**Issue by jovantanyk** [NUS-Fintech-Society/SD_DAO#33]
![image](https://user-images.githubusercontent.com/41192630/217007761-7ca7cbf9-553a-4eb9-985f-e87c7b98ebbc.png)
- [x] Project About Page design
- [x] Background
- [x] Edit Button to edit about text

Assigned to @loyhongshenggg

**Comment by loyhongshenggg** [comment]
![image](https://user-images.githubusercontent.com/97422591/218633568-df1de697-3c19-4dde-9012-73437acf4bd5.png)
(Before)

![image](https://user-images.githubusercontent.com/97422591/218634617-12fff141-e1c9-42cd-a04a-15269d8f3cc5.png)
(Edit about)

![image](https://user-images.githubusercontent.com/97422591/218634641-3acd1ced-ac28-4cde-a8a9-f934baa04e81.png)
(After edit)
