### ISSUE TITLE
Landing Page: Navbar

### ISSUE THREAD

**Issue by jovantanyk** [NUS-Fintech-Society/SD_DAO#7]
Transparent Navbar with Sign in Button

**Comment by SuperZecton** [comment]
Navbar for landing page completed, pending dynamic navbar when signed in and authenticated

**Comment by jovantanyk** [comment]
Pending Navbar:
- [ ] Transparent Navbar - Assigned to @Kappaccinoh 
- [ ] Updated navbar items to fit redesign - Assigned to @Kappaccinoh

**Comment by Kappaccinoh** [comment]
updated check pull request, thanks

**Comment by jovantanyk** [comment]
#26 Completed Navbar. Thanks @Kappaccinoh !
